const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const server = fs.readFileSync(path.join(root, "src", "server.js"), "utf8");
const app = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
const html = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
const dbIndex = fs.readFileSync(path.join(root, "src", "db", "index.js"), "utf8");

assert(server.includes("/api/login"), "API de login ausente");
assert(server.includes("/api/register"), "API de cadastro ausente");
assert(server.includes("/api/account-opening"), "API de abertura de conta ausente");
assert(server.includes("/api/reports/transactions.csv"), "API de relatorio CSV ausente");
assert(server.includes("/api/cards/purchase"), "API de compra no cartao ausente");
assert(server.includes("/api/investments/apply"), "API de investimentos ausente");
assert(server.includes("/api/loans/request"), "API de emprestimos ausente");
assert(server.includes("/api/password-reset/request"), "API de recuperacao de senha ausente");
assert(server.includes("/api/admin/account-opening/"), "API admin de aprovacao ausente");
assert(server.includes("/api/refresh"), "API refresh token ausente");
assert(server.includes("HttpOnly"), "Cookie HttpOnly ausente");
assert(server.includes("Content-Security-Policy"), "CSP ausente");
assert(server.includes("checkRateLimit"), "Rate limit ausente");
assert(server.includes("log(\"request\""), "Log de request ausente");
assert(server.includes("createStore"), "Store de banco ausente");
assert(server.includes("/api/reports/receipt.pdf"), "Comprovante PDF ausente");
assert(server.includes("pbkdf2Sync"), "Hash PBKDF2 ausente");
assert(server.includes("timingSafeEqual"), "Comparacao segura ausente");
assert(app.includes("validateCpf"), "Validacao de CPF no app ausente");
assert(app.includes("exportCsvButton"), "Exportacao CSV no app ausente");
assert(app.includes("renderFlowChart"), "Grafico de fluxo ausente");
assert(app.includes("cardPurchaseButton"), "Cartao no app ausente");
assert(app.includes("investmentApplyButton"), "Investimentos no app ausentes");
assert(app.includes("loanRequestButton"), "Emprestimos no app ausentes");
assert(app.includes("pdfReceiptButton"), "Botao PDF ausente");
assert(app.includes("showToast"), "Toasts ausentes");
assert(app.includes("setLoading"), "Loading ausente");
assert(app.includes("confirmAction"), "Confirmacoes ausentes");
assert(html.includes('id="onboarding"'), "Tela de abertura ausente");
assert(html.includes('id="reports"'), "Tela de relatorios ausente");
assert(html.includes('id="investments"'), "Tela de investimentos ausente");
assert(html.includes('id="resetPasswordButton"'), "Recuperacao de senha ausente");
assert(html.includes('terms.html'), "Link de termos ausente");
assert(html.includes('loadingOverlay'), "Overlay de loading ausente");
assert(fs.existsSync(path.join(root, "public", "privacy.html")), "Politica de privacidade ausente");
assert(dbIndex.includes("createPostgresStore"), "PostgreSQL store nao preparado");
assert(fs.existsSync(path.join(root, "docs", "migrations", "001_initial_schema.sql")), "Migration inicial ausente");
assert(fs.existsSync(path.join(root, ".github", "workflows", "ci.yml")), "CI ausente");

console.log("Nextt Bank: testes estruturais passaram.");
