-- Demo seed placeholder for PostgreSQL deployments.
-- Use this file after wiring the backend to PostgreSQL.

-- Suggested users:
-- cliente@nextt.local / password hash generated by the app
-- admin@nextt.local / password hash generated by the app
